language: ruby
cache: bundler # caching to speed up dependency installation
rvm:
- 2.4.1
before_install:
    - gem update --system
    - gem install bundler
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
jobs:
  include:
    - stage: build
      script: bundle exec jekyll build
    - stage: testlinks
      script: bundle exec jekyll build && bundle exec hmtlproofer ./_site --check-html
