name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Ruby, JRuby and TruffleRuby
      # You may pin to the exact commit or the version.
      # uses: ruby/setup-ruby@8bc9ca9ace0139aae24423f15269b9673354b495
        uses: ruby/setup-ruby@v1.46.1
        with:
          # Engine and version to use, see the syntax in the README. Reads from .ruby-version or .tool-versions if unset.
          ruby-version: 2.6.6 # optional, default is default
          # The version of Bundler to install. Either 'none', 1, 2, 'latest' or 'Gemfile.lock'.
          # For 'Gemfile.lock', the version is determined based on the BUNDLED WITH section from the file Gemfile.lock, $BUNDLE_GEMFILE.lock or gems.locked.
          # Defaults to 'Gemfile.lock' if the file exists and 'latest' otherwise.

          #bundler: "bundle install"  # optional, default is default
          # Run "bundle install", and cache the result automatically. Either true or false.
          #bundler-cache: # optional, default is false
          # The working directory to use for resolving paths for .ruby-version, .tool-versions and Gemfile.lock.
          #working-directory: # optional, default is .
      - name: install jekyll and test
        run: |
           - "bundle exec jekyll build"
           - "bundle exec htmlproofer --url-ignore '/cslabs' ./_site --check-html"
      - name: GitHub Releases
        # You may pin to the exact commit or the version.
        # uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f
        uses: fnkr/github-action-ghr@v1.3
      #- name: GitHub Upload Release Artifacts
        # You may pin to the exact commit or the version.
        # uses: Roang-zero1/github-upload-release-artifacts-action@f0677c0645db8d52dddaee4e83ce2c150f95e8e1
        #uses: Roang-zero1/github-upload-release-artifacts-action@v2.1.0
        #with:
          # Allows to pass an already created tag, forces update_existing to true.
          #created_tag: # optional, default is 
        
